FROM ubuntu:14.04
MAINTAINER Fabien Arcellier <fabien.arcellier@gmail.com>

RUN apt-get update && \
    apt-get install -y python3-dev && \
    apt-get install -y python3-pip && \
    apt-get install -y libssl-dev

RUN pip3 install ansible && \
    pip3 install pytest && \
    pip3 install testinfra

RUN mkdir -p '/etc/ansible' && \
    echo '[local]\nlocalhost ansible_connection=local\n' > /etc/ansible/hosts